import {ManualPage} from '../types';

export const manualPages: ManualPage[] = [
  {
    id: 'manual-1',
    pageNumber: 1,
    imageUrl: '/manual-pages/page-1.svg',
    title: 'Manual Page 1',
    translations: [
      { id: 'p1-placeholder-1', x: 52, y: 18, englishText: 'Placeholder translation', maxWidth: 24 },
      {
        id: 'p1-placeholder-2',
        x: 42,
        y: 72,
        englishText: 'Longer placeholder text wraps inside this box.',
        maxWidth: 30,
        fontSize: 0.85,
      },
    ],
  },
  {
    id: 'manual-2',
    pageNumber: 2,
    imageUrl: '/manual-pages/manual-2.png',
    title: 'Manual Page 2',
    translations: [
      { id: 'p2-placeholder-1', x: 30, y: 58, englishText: 'Cards', maxWidth: 22 },
      { id: 'p2-card2', x: 30, y: 64, englishText: 'wasd', maxWidth: 22 },
      { id: 'p2-card3', x: 67, y: 65, englishText: 'wasd', maxWidth: 22 },
    ],
  },
  {
    id: 'manual-3',
    pageNumber: 3,
    imageUrl: '/manual-pages/manual-3.png',
    title: 'Manual Page 3',
    translations: [
      { id: 'p3-placeholder-1', x: 30, y: 18, englishText: 'There lived a Civilization of gpayt ___ . They built a city, and within* that city they built a palace. They held sacred the secrets of the Holy Cross, and ad_st_d the plain__', maxWidth: 40}],
  },
  {
    id: 'manual-4',
    pageNumber: 4,
    imageUrl: '/manual-pages/manual-4.png',
    title: 'Manual Page 4',
    translations: [{ id: 'p4-placeholder-1', x: 48, y: 60, englishText: 'Manual translation', maxWidth: 24 }],
  },
  {
    id: 'manual-5',
    pageNumber: 5,
    imageUrl: '/manual-pages/manual-5.png',
    title: 'Manual Page 5',
  },
  {
    id: 'manual-6',
    pageNumber: 6,
    imageUrl: '/manual-pages/manual-6.png',
    title: 'Manual Page 6',
  },
  {
    id: 'manual-7',
    pageNumber: 7,
    imageUrl: '/manual-pages/manual-7.png',
    title: 'Manual Page 7',
  },
  {
    id: 'manual-8',
    pageNumber: 8,
    imageUrl: '/manual-pages/manual-8.png',
    title: 'Manual Page 8',
  },
  {
    id: 'manual-9',
    pageNumber: 9,
    imageUrl: '/manual-pages/manual-9.png',
    title: 'Manual Page 9',
  },
  {
    id: 'manual-10',
    pageNumber: 10,
    imageUrl: '/manual-pages/manual-10.png',
    title: 'Manual Page 10',
  },
  {
    id: 'manual-11',
    pageNumber: 11,
    imageUrl: '/manual-pages/manual-11.png',
    title: 'Manual Page 11',
  },
  {
    id: 'manual-12',
    pageNumber: 12,
    imageUrl: '/manual-pages/manual-12.png',
    title: 'Manual Page 12',
  },
  {
    id: 'manual-13',
    pageNumber: 13,
    imageUrl: '/manual-pages/manual-13.png',
    title: 'Manual Page 13',
  },
  {
    id: 'manual-14',
    pageNumber: 14,
    imageUrl: '/manual-pages/manual-14.png',
    title: 'Manual Page 14',
  },
  {
    id: 'manual-15',
    pageNumber: 15,
    imageUrl: '/manual-pages/manual-15.png',
    title: 'Manual Page 15',
  },
  {
    id: 'manual-16',
    pageNumber: 16,
    imageUrl: '/manual-pages/manual-16.png',
    title: 'Manual Page 16',
  },
  {
    id: 'manual-17',
    pageNumber: 17,
    imageUrl: '/manual-pages/manual-17.png',
    title: 'Manual Page 17',
  },
  {
    id: 'manual-18',
    pageNumber: 18,
    imageUrl: '/manual-pages/manual-18.png',
    title: 'Manual Page 18',
  },
  {
    id: 'manual-19',
    pageNumber: 19,
    imageUrl: '/manual-pages/manual-19.png',
    title: 'Manual Page 19',
  },
  {
    id: 'manual-20',
    pageNumber: 20,
    imageUrl: '/manual-pages/manual-20.png',
    title: 'Manual Page 20',
  },
  {
    id: 'manual-21',
    pageNumber: 21,
    imageUrl: '/manual-pages/manual-21.png',
    title: 'Manual Page 21',
  },
  {
    id: 'manual-22',
    pageNumber: 22,
    imageUrl: '/manual-pages/placeholder.png',
    title: 'Manual Page 22',
  },
  {
    id: 'manual-23',
    pageNumber: 23,
    imageUrl: '/manual-pages/placeholder.png',
    title: 'Manual Page 23',
  },
  {
    id: 'manual-24',
    pageNumber: 24,
    imageUrl: '/manual-pages/manual-24.png',
    title: 'Manual Page 24',
  },
  {
    id: 'manual-25',
    pageNumber: 25,
    imageUrl: '/manual-pages/manual-25.png',
    title: 'Manual Page 25',
  },
  {
    id: 'manual-26',
    pageNumber: 26,
    imageUrl: '/manual-pages/manual-26.png',
    title: 'Manual Page 26',
  },
  {
    id: 'manual-27',
    pageNumber: 27,
    imageUrl: '/manual-pages/manual-27.png',
    title: 'Manual Page 27',
  },
  {
    id: 'manual-28',
    pageNumber: 28,
    imageUrl: '/manual-pages/manual-28.png',
    title: 'Manual Page 28',
  },
  {
    id: 'manual-29',
    pageNumber: 29,
    imageUrl: '/manual-pages/manual-29.png',
    title: 'Manual Page 29',
  },
  {
    id: 'manual-30',
    pageNumber: 30,
    imageUrl: '/manual-pages/manual-30.png',
    title: 'Manual Page 30',
  },
  {
    id: 'manual-31',
    pageNumber: 31,
    imageUrl: '/manual-pages/manual-31.png',
    title: 'Manual Page 31',
  },
  {
    id: 'manual-32',
    pageNumber: 32,
    imageUrl: '/manual-pages/manual-32.png',
    title: 'Manual Page 32',
  },
  {
    id: 'manual-33',
    pageNumber: 33,
    imageUrl: '/manual-pages/manual-33.png',
    title: 'Manual Page 33',
  },
  {
    id: 'manual-34',
    pageNumber: 34,
    imageUrl: '/manual-pages/manual-34.png',
    title: 'Manual Page 34',
  },
  {
    id: 'manual-35',
    pageNumber: 35,
    imageUrl: '/manual-pages/manual-35.png',
    title: 'Manual Page 35',
  },
  {
    id: 'manual-36',
    pageNumber: 36,
    imageUrl: '/manual-pages/manual-36.png',
    title: 'Manual Page 36',
  },
  {
    id: 'manual-37',
    pageNumber: 37,
    imageUrl: '/manual-pages/manual-37.png',
    title: 'Manual Page 37',
  },
  {
    id: 'manual-38',
    pageNumber: 38,
    imageUrl: '/manual-pages/manual-38.png',
    title: 'Manual Page 38',
  },
  {
    id: 'manual-39',
    pageNumber: 39,
    imageUrl: '/manual-pages/manual-39.png',
    title: 'Manual Page 39',
  },
  {
    id: 'manual-40',
    pageNumber: 40,
    imageUrl: '/manual-pages/manual-40.png',
    title: 'Manual Page 40',
  },
  {
    id: 'manual-41',
    pageNumber: 41,
    imageUrl: '/manual-pages/manual-41.png',
    title: 'Manual Page 41',
  },
  {
    id: 'manual-42',
    pageNumber: 42,
    imageUrl: '/manual-pages/manual-42.png',
    title: 'Manual Page 42',
  },
  {
    id: 'manual-43',
    pageNumber: 43,
    imageUrl: '/manual-pages/manual-43.png',
    title: 'Manual Page 43',
  },
  {
    id: 'manual-44',
    pageNumber: 44,
    imageUrl: '/manual-pages/manual-44.png',
    title: 'Manual Page 44',
  },
  {
    id: 'manual-45',
    pageNumber: 45,
    imageUrl: '/manual-pages/manual-45.png',
    title: 'Manual Page 45',
  },
  {
    id: 'manual-46',
    pageNumber: 46,
    imageUrl: '/manual-pages/manual-46.png',
    title: 'Manual Page 46',
  },
  {
    id: 'manual-47',
    pageNumber: 47,
    imageUrl: '/manual-pages/manual-47.png',
    title: 'Manual Page 47',
  },
  {
    id: 'manual-48',
    pageNumber: 48,
    imageUrl: '/manual-pages/manual-48.png',
    title: 'Manual Page 48',
  },
  {
    id: 'manual-49',
    pageNumber: 49,
    imageUrl: '/manual-pages/manual-49.png',
    title: 'Manual Page 49',
  },
  {
    id: 'manual-50',
    pageNumber: 50,
    imageUrl: '/manual-pages/manual-50.png',
    title: 'Manual Page 50',
  },
  {
    id: 'manual-51',
    pageNumber: 51,
    imageUrl: '/manual-pages/manual-51.png',
    title: 'Manual Page 51',
  },
  {id: 'manual-52',
    pageNumber: 52,
    imageUrl: '/manual-pages/manual-52.png',
    title: 'Manual Page 52',
  },
];
